# -*- coding: utf-8 -*-
# @Author: rajeshneti
# @Date:   2018-04-08 16:07:36
# @Last Modified by:   rajeshneti
# @Last Modified time: 2018-04-08 17:18:57
sites=["answers.com","ask.com","blogger.com", "facebook.com", "flickr.com" ,"girlsaskguys.com" ,"imgur.com","instagram.com","last.fm",
		"libre.fm","linkedin.com","match.com","pinterest.com","quora.com","raptr.com","reddit.com","stackoverflow.com" ,"tripadvisor.com","tumblr.com",
		"twitter.com","viadeo.com","wikipedia.org","wordpress.org","xing.com","yelp.com","youtube.com"]
s1=["http://www.answers.com/","https://www.answers.com/Q/FAQ/5091","http://www.answers.com/Q/FAQ/2885","https://www.answers.com/Q/FAQ/7493","https://www.answers.com/Q/FAQ/4148-2","http://wiki.answers.com/help/asking_questions","http://www.answers.com/Q/FAQ/1839","https://www.answers.com/Q/FAQ/7505-2","https://www.answers.com/Q/FAQ/10447-3","http://www.answers.com/Q/FAQ/2148"]
s2=["http://help.ask.com/link/portal/30015/30018/ArticleFolder/11/Ask-com-Browser-Toolbar","http://help.ask.com/ics/support/default.asp?deptID=30018&task=knowledge&questionID=230","https://hp.tb.ask.com/tbask/index.html?p2=^UX^xdm578^S10474^us&n=780c7317&ptb=22D0EFEF-1AF4-4911-BE20-67F032677E7D&qs=fn","https://help.ask.com/link/portal/30015/30018/ArticleFolder/10/Ask-com-Search","http://help.ask.com/link/portal/30015/30018/Article/1/How-do-I-remove-the-Ask-com-Toolbar","http://help.ask.com/ics/support/default.asp?deptID=30018","http://help.ask.com/link/portal/30015/30018/Article/134","https://www.ask.com/","http://apn.ask.com/","http://hp.ask.com/onlinemapfinder/s16311/index.html?p2=%5EBA5%5Exdm133%5ES16351%5Eus&ptb=DD4D7D76-555A-4CB8-A6AA-A6DD9B840CC7&si=245051_Work-ieff&n=782A33E4"]
s3=["https://www.blogger.com/home","https://blogger.com/editor/static_files/blank_quirks.html","https://www.blogger.com/login.g","https://www.blogger.com/profile/12522565235980454675","https://www.blogger.com/?rinli=1","https://www.blogger.com/profile/04486298891295312827","https://www.blogger.com/profile/10316114807344544892","https://www.blogger.com/profile/16820399856274245684","https://www.blogger.com/profile/14340145740286368529","https://www.blogger.com/content.g?hl=en&authuser=0&bpli=1"]
s4=["http://www.facebook.com/r.php","http://www.facebook.com/Bing","https://apps.facebook.com/criminalcase/","https://mbasic.facebook.com/","http://www.facebook.com/find-friends/","https://apps.facebook.com/wordswithfriends/","https://www.facebook.com/recover/initiate","http://www.facebook.com/people-search.php","http://www.facebook.com/youtube","http://www.facebook.com/help/"]
s5=["https://www.flickr.com/photos/tags/stormydaniels/","https://www.flickr.com/","https://www.flickr.com/photos/tags/ladyboy/","https://www.flickr.com/photos/tags/sexyfeet/","https://www.flickr.com/photos/tags/cunts/","https://www.flickr.com/photos/12958857@N05/","https://www.flickr.com/photos/blue-diesels/","https://www.flickr.com/photos/","https://www.flickr.com/tools/","https://www.flickr.com/photos/76237188@N03/favorites/"]
s6=["https://www.girlsaskguys.com/","https://www.girlsaskguys.com/ask-question","https://www.girlsaskguys.com/social-relationships/q57326-truth-questions","https://www.girlsaskguys.com/guys-behavior","https://www.girlsaskguys.com/sexual-health/q112174-is-6-5-inches-small","https://www.girlsaskguys.com/girls-behavior","https://www.girlsaskguys.com/sexual-behavior","https://www.girlsaskguys.com/flirting","https://www.girlsaskguys.com/dating/q2604614-match-com-question-what-does-the-open-green-circle-mean-how-long","https://www.girlsaskguys.com/guys-behavior/q784410-why-against-law-for-person-living-in"]
s7=["https://i.imgur.com/wrDS2xn.gifv","https://i.imgur.com/Ar4Y2m8.gifv","https://i.imgur.com/Ar91xOK.gifv","https://i.imgur.com/K1uwXen.gifv","https://i.imgur.com/SbPCocn.gifv","https://i.imgur.com/fkhklEX.gifv","https://i.imgur.com/FWSntf7.gifv","https://i.imgur.com/CUrslNO.gifv","https://i.imgur.com/zzKK9Hl.gifv","https://i.imgur.com/ZPFcffq.gifv"]
s8=["https://www.instagram.com/explore/tags/kathniel/","https://www.instagram.com/explore/tags/fiftyshadesfreed/","https://www.instagram.com/explore/tags/helenefischer/","https://www.instagram.com/explore/tags/tïts/","https://www.instagram.com/explore/tags/justinbieber/","https://www.instagram.com/explore/tags/nadechyaya/","https://www.instagram.com/explore/tags/brumar/","https://www.instagram.com/explore/tags/fitness/","https://www.instagram.com/explore/tags/jelena/","https://www.instagram.com/1789_toho/"]
s9=["https://www.last.fm/","https://www.last.fm/music/Atif+Aslam","https://www.last.fm/music","https://www.last.fm/music/Kishore+Kumar","https://www.last.fm/music/Westlife","https://www.last.fm/music/jj","https://www.last.fm/music/+free-music-downloads","https://www.last.fm/join","https://www.last.fm/music/Maher+Zain","https://secure.last.fm/login"]
s10=["https://libre.fm/login.php","https://libre.fm/listen.php?tag=classical","https://libre.fm/register.php","https://libre.fm/reset.php","https://libre.fm/user/RJules3/stats","https://libre.fm/user/jonwarren/stats","https://libre.fm/","https://libre.fm/artist/Alexander+Blu/","http://turtle.libre.fm/","https://libre.fm/listen.php"]
s11=["https://in.linkedin.com/","https://www.linkedin.com/uas/login","https://www.linkedin.com/company/login","https://developer.linkedin.com/","https://business.linkedin.com/sales-solutions/sales-navigator","https://www.linkedin.com/company/l&t-infotech","https://business.linkedin.com/marketing-solutions/company-pages","https://business.linkedin.com/marketing-solutions/ads","https://www.linkedin.com/post/new","https://business.linkedin.com/"]
s12=["https://www4.match.com/login","https://in.match.com/login/forgotemail/","https://www4.match.com/logout/?lid=3","https://www.match.com/cpx/en-us/landing/display/84123/","https://www.match.com/","https://datingtips.match.com/flirt-girl-chatting-13197209.html","https://ie.match.com/","https://www.match.com/cpx/en-us/partner/yahoo/channel/","http://careers.match.com/","https://ie.match.com/m/"]
s13=["https://www.pinterest.com/","https://www.pinterest.com/explore/junk-art/","https://www.pinterest.com/pin/573223858791988548/","https://www.pinterest.com/explore/seasons-kindergarten/","https://www.pinterest.com/pin/567172146804044781/","https://www.pinterest.com/explore/cute-dog-quotes/","https://www.pinterest.com/pin/507006870530099894/","https://www.pinterest.com/pin/283726845253029618/","https://www.pinterest.com/pin/84583299225144026/","https://www.pinterest.com/pin/146226319124661185/"]
s14=["https://www.quora.com/What-is-the-password-to-open-an-e-Aadhaar-card","https://www.quora.com/","https://www.quora.com/topic/China","https://www.quora.com/How-many-watts-are-equal-to-1-unit-in-an-electricity-bill","https://www.quora.com/How-do-you-track-a-Western-Union-money-order-online","https://www.quora.com/How-much-is-one-million-and-one-billion-in-lakhs-and-crores","https://www.quora.com/How-do-I-disable-Windows-10-update-assistant","https://supermonk.quora.com/","https://www.quora.com/How-much-money-in-US-dollars-is-1-crore-rupees","https://www.quora.com/What-can-cause-foam-to-come-out-from-the-mouth-and-nose-of-a-dead-body"]
s15=["http://raptr.com/amd","http://raptr.com/","http://raptr.com/bestiality/games","http://raptr.com/community/highlights/discussions","http://raptr.com/download","http://about.raptr.com/goodbye-raptr/","http://raptr.com/amd/games","http://about.raptr.com/","http://raptr.com/login/reset","http://raptr.com/free-games"]
s16=["https://www.reddit.com/","https://www.reddit.com/r/soccer/","https://www.reddit.com/r/aww/comments/83psdv/neighboring_husky_boi_returns_an_awoo/","https://www.reddit.com/r/movies/comments/828cyn/john_boyega_here_ask_me_anything/","https://reddit.com/r/ChoosingBeggars/comments/83ftyj/this_other_person_i_hired_sucks_so_i_want_to_hire/","https://www.reddit.com/r/xboxone/","https://reddit.com/r/mildlyinfuriating/comments/8166ul/these_pencils_suck/","https://www.reddit.com/r/wholesomebpt/comments/82fqzs/good_deeds_and_blooming_seeds/","https://www.reddit.com/r/SheBelievesCup2018/","https://reddit.com/r/news/comments/825i4n/north_korea_made_as_much_as_200_million_from/"]
s17=["https://stackoverflow.com/","https://stackoverflow.com/questions/6288122/checking-oracle-sid-and-database-name","https://stackoverflow.com/questions/10195451/sql-inner-join-with-3-tables","https://stackoverflow.com/questions/11824501/inner-joining-three-tables","https://stackoverflow.com/questions/19641597/what-is-segmentation-fault-core-dumped","https://stackoverflow.com/questions/5774970/run-jar-file-in-command-prompt","https://stackoverflow.com/questions/29432629/correlation-matrix-using-pandas","https://stackoverflow.com/jobs","https://stackoverflow.com/questions/19721416/formula-to-convert-date-to-number","https://stackoverflow.com/questions/15675414/add-attachement-to-outlook-with-varying-file-names"]
s18=["https://www.tripadvisor.com/","https://www.tripadvisor.com/Attractions-g188590-Activities-Amsterdam_North_Holland_Province.html","https://www.tripadvisor.com/Attractions-g35805-Activities-Chicago_Illinois.html","https://www.tripadvisor.com/Attractions-g187147-Activities-Paris_Ile_de_France.html","https://www.tripadvisor.com/Attractions-g45963-Activities-Las_Vegas_Nevada.html","https://www.tripadvisor.com/Attractions-g60878-Activities-Seattle_Washington.html","https://www.tripadvisor.com/Attractions-g293974-Activities-Istanbul.html","https://www.tripadvisor.com/Attractions-g60713-Activities-San_Francisco_California.html","https://www.tripadvisor.com/Hotels-g294217-Hong_Kong-Hotels.html","https://www.tripadvisor.com/Hotels"]
s19=["https://www.tumblr.com/","http://srbachchan.tumblr.com/","http://wikihow.tumblr.com/","https://obscurus-sims.tumblr.com/","https://pasldan.tumblr.com/dasibogitv","http://guncontrolmarch.tumblr.com/","http://reallyfunnyjokes.tumblr.com/","http://russia-instagram.tumblr.com/","http://jessiichavez.tumblr.com/","http://badkidsjokes.tumblr.com/"]
s20=["https://mobile.twitter.com/account","https://tweetdeck.twitter.com/","https://twitter.com/login/","https://ads.twitter.com/","https://twitter.com/asadowaisi","https://twitter.com/ideacellular","https://twitter.com/sciencedaily","https://business.twitter.com/","https://analytics.twitter.com/","https://about.twitter.com/"]
s21=["http://in.viadeo.com/en/","http://in.viadeo.com/en/profile/capitalstars.financial.research","http://in.viadeo.com/en/profile/boris.denoual","http://in.viadeo.com/en/profile/pooja-singh.bhandari1","http://in.viadeo.com/en/profile/somnath.chatterjee12","http://in.viadeo.com/en/profile/vijendra.poonia","http://in.viadeo.com/en/groups/?containerId=002rhucs3dgvqqu","http://in.viadeo.com/en/profile/sridevi.rao","http://in.viadeo.com/en/questions/repondre/?questionId=0021y0smng6owspm","http://www.viadeo.com/en/mentions-legales"]
s22=["https://en.wikipedia.org/wiki/CAPTCHA","https://simple.wikipedia.org/wiki/Rain","https://en.wikipedia.org/wiki/Sachin_(actor)","https://simple.wikipedia.org/wiki/Hindi","https://simple.wikipedia.org/wiki/Wikipedia:Basic_English_picture_wordlist","https://en.wikipedia.org/wiki/Amroha","https://en.wikipedia.org/wiki/Confusion","https://en.wikipedia.org/wiki/Extranet","https://en.wikipedia.org/wiki/Organza","https://en.wikipedia.org/wiki/HSE"]
s23=["https://wordpress.org/","https://codex.wordpress.org/Child_Themes","https://codex.wordpress.org/Twenty_Seventeen","https://codex.wordpress.org/WordPress_Widgets","https://codex.wordpress.org/","https://codex.wordpress.org/New_To_WordPress_-_Where_to_Start","https://wordpress.org/download/","https://codex.wordpress.org/Updating_WordPress","https://codex.wordpress.org/CSS","https://wordpress.org/showcase/"]
s24=["https://www.xing.com/en","https://dev.xing.com/developers","https://www.xing.com/xtm","https://recruiting.xing.com/en/contact/","https://www.xing.com/jobmanager/products","https://recruiting.xing.com/en/","https://tech.xing.com/","https://dev.xing.com/plugins/login_with","https://dev.xing.com/logo_rules","https://corporate.xing.com/fileadmin/department/investorrelations/Publikationen/XING_AG_results_FY_2012.pdf"]
s25=["https://yelp.com/biz/eastern-bloc-new-york","https://yelp.com/biz/mokai-lounge-miami-beach","https://www.yelp.com/biz/access-insurance-company-atlanta-2","https://yelp.com/biz/torchys-tacos-austin","https://yelp.com/biz/oriental-buffet-sarasota","https://yelp.com/biz/tasty-made-lancaster","https://yelp.com/biz/carvalhos-brazilian-kitchen-scottsdale","https://yelp.com/biz/deluxe-station-diner-newton","https://www.yelp.com/biz/luscious-dumplings-san-gabriel-3","https://yelp.com/biz/now-and-then-second-hand-store-orange"]
s26=["https://gaming.youtube.com/","https://www.youtube.com/advanced_settings","https://www.youtube.com/watch?v=9Bxik6kLEbM","https://gaming.youtube.com/ice_poseidon/live","https://www.youtube.com/watch?v=38aIMNJKS-g","https://gaming.youtube.com/Swaggxbl","https://youtube.com/watch?v=qt4v-kXP8F4","https://youtube.com/watch?v=_I_D_8Z4sJE","https://www.youtube.com/watch?v=Ya_4C3jSsn0","https://youtube.com/watch?v=P6CwU6i6ick"]
