# -*- coding: utf-8 -*-
# @Author: vamshi
# @Date:   2018-04-14 14:36:50
# @Last Modified by:   vamshi
# @Last Modified time: 2018-04-16 23:27:35
sites=["answers.com","ask.com","blogger.com", "facebook.com", "flickr.com" ,"girlsaskguys.com" ,"imgur.com","instagram.com","last.fm",
		"libre.fm","linkedin.com","match.com","pinterest.com","quora.com","raptr.com","reddit.com","stackoverflow.com" ,"tripadvisor.com","tumblr.com",
		"twitter.com","viadeo.com","wikipedia.org","wordpress.org","xing.com","yelp.com","youtube.com"]

s1=["http://www.answers.com/","http://www.answers.com/Q/","http://www.answers.com/Q/What_is_the_value_of_a_1915_Susan_B_Anthony_half_Dollar","http://www.answers.com/Q/What_did_Grandma_Moses_children_call_her","http://www.answers.com/Q/What_is_the_phone_number_of_the_Mount_Carmel_Library_in_Mount_Carmel","http://www.answers.com/Q/Did_Moses_really_cross_the_red_sea","http://www.answers.com/Q/Can_you_travel_with_a_gas_stove_lighter_on_an_airplane","http://qa.answers.com/Q/What_river_flowing_to_the_Mediterranean_starts_with_the_letter_E","http://qa.answers.com/Q/Is_Africa_in_the_Middle_East_or_southeast","http://www.answers.com/Q/Did_hitler_invading_sweeden_start_World_War_2"]
s2=["https://www.reference.com/science","https://www.reference.com/education","https://www.reference.com/technology","https://www.reference.com/geography","https://www.reference.com/food","https://www.reference.com/history","https://www.reference.com/history","https://www.reference.com/history","https://www.reference.com/history","https://www.reference.com/history"]
s3=["https://www.blogger.com/about/?r=2","https://plus.google.com/118027515659458990484","https://plus.google.com/113348569517506764394","https://plus.google.com/110628371959257478941","https://plus.google.com/+fuxoft","https://www.blogger.com/profile/1","https://productforums.google.com/forum/?authuser=0#!forum/blogger","https://productforums.google.com/forum/#!forum/blogger","https://plus.google.com/+GuilleSGOTTLOSEN","https://plus.google.com/111188340418150286510"]
s4=["https://www.facebook.com/pasargadtabac/","https://www.facebook.com/BritesideDelivery/","https://www.facebook.com/JesusCalling/","https://www.facebook.com/newyou6weekchallenge/","https://www.facebook.com/feminamissindia/","https://www.facebook.com/marathigirls11/","https://www.facebook.com/ktla5/","https://www.facebook.com/psbacademy/","https://www.facebook.com/soundheartsfestival/","https://www.facebook.com/Ddfreekibaat/"]
s5=["https://www.flickr.com/creativecommons/?ytcheck=1&new_session=1","https://www.flickr.com/cameras?ytcheck=1&new_session=1","https://www.flickr.com/?ytcheck=1&new_session=1","https://flickr.com/","https://www.flickr.com/create","https://www.flickr.com/explore/","https://www.flickr.com/photos/flickr/galleries?rb=1","https://www.flickr.com/map","https://www.flickr.com/photos/crehealth","https://www.flickr.com/photos/laurattphoto"]
s6=["https://www.girlsaskguys.com/topics","https://www.girlsaskguys.com/popular","https://www.girlsaskguys.com/dating","https://www.girlsaskguys.com/poll","https://www.girlsaskguys.com/relationships","https://www.girlsaskguys.com/no-opinions","https://www.girlsaskguys.com/live-feed","https://www.girlsaskguys.com/guys-behavior","https://www.girlsaskguys.com/technology-internet","https://www.girlsaskguys.com/dating/q3069693-stranger-dating"]
s7=["https://imgur.com/","https://imgur.com/memegen","https://smarteck.imgur.com/","https://imgurinc.com/press/","https://imgur.com/gallery","https://underworldlarp.imgur.com/","https://imgur.com/dooS7Dk","https://cavinanderson.imgur.com/","https://imgur.com/PWgkluX","https://imgur.com/AHYwI9m"]
s8=["https://www.instagram.com/juandediospantoja/","https://www.instagram.com/mangekimambi_/","https://www.instagram.com/um_naif_5/","https://www.instagram.com/carolinacruzosorio/","https://www.instagram.com/sophiefontanel/","https://www.instagram.com/baileysok1/","https://www.instagram.com/sebastianyatra/","https://www.instagram.com/gracielelacerdaoficial/","https://www.instagram.com/lokhandeankita/","https://www.instagram.com/757cece/"]
s9=["https://www.last.fm/","https://www.last.fm/events","https://www.last.fm/api","https://build.last.fm/","https://www.last.fm/about","https://www.last.fm/features","https://www.last.fm/passwordsecurity","https://www.last.fm/musicmanager","http://status.last.fm/","https://www.last.fm/subscribe"]
s10=["https://libre.fm/podcast","https://libre.fm/","https://libre.fm/api/","https://turtle.libre.fm/","https://libre.fm/user/balleyne","https://libre.fm/user/tobyink","https://libre.fm/listen.php","https://libre.fm/donate.php","https://libre.fm/register.php","https://libre.fm/login.php"]
s11=["https://www.microsoft.com/en-us/investor/","https://www.linkedin.com/in/sladner","https://www.linkedin.com/school/ist/","https://in.linkedin.com/jobs/","https://www.linkedin.com/school/fiap/","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQE9CH6GP5VSUAAAAWLNUmWAgUjHbeUj-mceW4XHLzvxopxMgzfcoUP7421gd5qc-HaC9U-KjXSQX-De6gwz-OY0bEoHmRkXva91V3nsJQ2arElHsTYZcbtht4PRHiIsmoWrJ7o=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAwwa7HAx.;_ylu=X3oDMTEyMWU3cWt0BGNvbG8Dc2czBHBvcwM2BHZ0aWQDQjEzOThfMQRzZWMDc3I-/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fin%2fblouvet&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fblouvet%2F","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQHJSs3XiwVj1gAAAWLNUm1QnHOVebnyPYzIj-ElL_RxMR8rAKkRAcQG9h5xSKSip7WEE81c6I6jPE-EoawJY9NVRE8j3kiynrIiK4vHJDHt8g_dgCoe4lmpwlbgYBC3Gwtiqmc=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAxAa7HAx.;_ylu=X3oDMTEyaG84OWRlBGNvbG8Dc2czBHBvcwM3BHZ0aWQDQjEzOThfMQRzZWMDc3I-/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fin%2fbrockfe&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fbrockferguson","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQGXa4vX5oV9_gAAAWLNUoiogXdM8LCP7ffuVwzavdK74rwUxJwSacVlBRXIk9ESoG3J43plIzLiepYwvQuYXZosMQDEpInHl-WOL0guwqNZkifrmJ2UCW3AHYsBd_UKRwTCaKs=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAxga7HAx.;_ylu=X3oDMTEyMWU5dm1tBGNvbG8Dc2czBHBvcwM5BHZ0aWQDQjEzOThfMQRzZWMDc3I-/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fcompany%2fpe&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fpearson","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQHtoL-J_ZLIqAAAAWLNUoyQTsxNJKEbCszCJ4tdxkRbPKCBYhzb9VoKT_D3ySAUAzRr_0A5Yi4SqGW0PQF9xcmrbxDvV3ZKy-i3UJyGanxOvFJYGlzdcpPM2Iiiz7ePxAATQrQ=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAxwa7HAx.;_ylu=X3oDMTEzZGNuYzczBGNvbG8Dc2czBHBvcwMxMAR2dGlkA0IxMzk4XzEEc2VjA3Ny/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fcompany%2fxi&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fxilinx","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQGCsfVOIsbvcgAAAWLNUoyQkbunGO64C3oEb3kaQzi_OBqLNIiA0W-PrJEQKhNqCu1ksQR9nIO9BzrDIQdk_7ystb5sgaHh8tUXmwhZ6DvRkVCWkc6rZcLkZERKMHkoQ1Zp9W8=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAxQa7HAx.;_ylu=X3oDMTEyYmg5dHNsBGNvbG8Dc2czBHBvcwM4BHZ0aWQDQjEzOThfMQRzZWMDc3I-/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fin%2fvincent&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fvincentgrady"]
s12=["https://ie.match.com/","https://in.match.com/dnws/cpx/intl/match/IndexPage/","http://www.match.com.ve/","https://in.match.com/dnws/magazine/","https://th.match.com/dnws/cpx/intl/match/IndexPage/","http://latino.match.com/","https://datingtips.match.com/","https://sg.match.com/dnws/cpx/intl/match/IndexPage/","https://in.match.com/dnws/help/help.aspx","https://in.match.com/dnws/hostevent/"]
s13=["https://in.pinterest.com/crpolo1/?autologin=true","https://in.pinterest.com/lea7505/","https://in.pinterest.com/jennydasilvamar/","https://in.pinterest.com/msladyleo04/?autologin=true","https://in.pinterest.com/aranthechef/","https://in.pinterest.com/yuwdhie7/","https://in.pinterest.com/bethanyellen7/?autologin=true","https://in.pinterest.com/kdbug2999/?autologin=true","https://in.pinterest.com/abbysalright/?autologin=true","https://in.pinterest.com/someblackguy087/"]
s14=["https://blog.quora.com/","https://thatsiitk.quora.com/","https://business.quora.com/","https://kavitaa.quora.com/","https://debunkingdoomsday.quora.com/","https://supermonk.quora.com/","https://de.quora.com/join?code=0&join_source=1&ref","https://megaflix69.quora.com/","https://alison60.quora.com/","https://it.quora.com/join?code=0&join_source=1&ref"]
s15=["http://raptr.com/","http://raptr.com/eisserjuriya/wall","http://raptr.com/thegeneralnws/wall","http://raptr.com/haley/wall","http://raptr.com/download","http://raptr.com/amd","http://raptr.com/intel","http://raptr.com/raptr_master","http://raptr.com/lgc41986/wall","http://raptr.com/borrylord/about"]
s16=["https://www.reddit.com/r/NBAPlayoffs_2018/comments/8chp81/freereddit_stream_pacers_vs_cavaliers_2018/","https://www.reddit.com/r/WorldSportslivefree/comments/8c7w6t/watchswansea_city_vs_everton_live_stream_2018/","https://www.reddit.com/r/WarriorsvsSpursLive/comments/8chcb6/livefreebasketball_indiana_pacers_vs_cleveland/","https://www.reddit.com/r/WarriorsvsSpursLive/comments/8cfmvv/watchhdmanchester_united_vs_west_brom_live_stream/","https://www.reddit.com/r/ChiefsvsHurricanesliv/comments/8c8d2e/livefreefight_ksw_43_soldic_vs_du_plessis_live/","https://www.reddit.com/r/nascarliveupdate/comments/8ch916/watchfreenascar_cup_series_food_city_500_live/","https://www.reddit.com/r/AmstelGoldRace2018/comments/8cfrrq/tro_bro_leon_2018_live_stream_reddit_free/","https://www.reddit.com/r/WarriorsvsSpursLive/comments/8cgpnc/angels_vs_royals_live_stream_reddit_free/","https://www.reddit.com/r/WorldSportslivefree/comments/8c7uhi/epl_streams_crystal_palace_vs_brighton_and_ha/","https://www.reddit.com/r/nba/comments/8ch3y4/game_thread_indiana_pacers_4834_cleveland/"]
s17=["https://stackoverflow.com/","https://es.stackoverflow.com/","https://stackoverflow.blog/","https://stackoverflow.com/jobs","https://www.youtube.com/watch?v=9UZbGgXvCCA","https://insights.stackoverflow.com/trends","https://stackoverflow.com/questions","https://insights.stackoverflow.com/survey/2016","https://insights.stackoverflow.com/trends?tags=r%2Cstatistics","https://insights.stackoverflow.com/survey/2018/"]
s18=["https://www.tripadvisor.in/","https://careers.tripadvisor.com/","https://itunes.apple.com/app/tripadvisor-hotels-flights-restaurants/id284876795?mt=8","https://www.tripadvisor.com/TravelersChoice","https://www.tripadvisor.com/VacationRentalsBlog/","https://www.tripadvisor.com/members/474andyt","https://www.tripadvisor.com/members/JoeyIamarino","https://www.tripadvisor.com/members/wendylB3942PW","https://www.tripadvisorsupport.com/hc/en-us/articles/200614797","https://www.tripadvisorsupport.com/hc/en-us/articles/200615037"]
s19=["https://www.tumblr.com/","http://hello8920.tumblr.com/","http://hd.clarin.com/","https://martinvaldezphoto.com/","https://finofilipino.org/","http://the-five-hundred.com/","https://nasa.tumblr.com/","http://whatpumpkin.tumblr.com/","http://beatrizcraven.com/","https://p4zeequilibrio.tumblr.com/"]
s20=["https://twitter.com/instagram","https://twitter.com/ea","https://twitter.com/russianembassy","https://twitter.com/eminem","https://twitter.com/barackobama","https://twitter.com/bet49s","https://twitter.com/prefpolice","https://twitter.com/realdonaldtrump","https://twitter.com/poetastrologers","https://twitter.com/marvel"]
s21=["https://dz.viadeo.com/en/","http://www.figaroclassifieds.fr/pages/7018-emploi","https://sn.viadeo.com/en/","https://lu.viadeo.com/en/","https://ci.viadeo.com/en/","https://mg.viadeo.com/en/","https://bf.viadeo.com/en/","https://cd.viadeo.com/en/","https://ca.viadeo.com/en/","https://ch.viadeo.com/en/"]
s22=["https://www.wikipedia.org/","https://en.wikipedia.org/wiki/Ben_Baldanza","https://pl.wikipedia.org/wiki/Kieran_Trippier","https://en.wikipedia.org/wiki/Braille","https://pl.wikipedia.org/wiki/Codogno","https://en.wikipedia.org/wiki/Bebop_scale","https://en.wikipedia.org/wiki/Patrick_Cramer","https://en.wikipedia.org/wiki/Varun_Sharma","https://en.wikipedia.org/wiki/Anna_Castillo","https://en.wikipedia.org/wiki/Access_Point_Name"]
s23=["https://apps.wordpress.com/support/","https://make.wordpress.org/cli/","https://apps.wordpress.com/contribute/","https://apps.wordpress.com/","https://wordpress.org/about/","https://wordpress.org/themes/","https://wordpress.org/gutenberg/","https://planet.wordpress.org/","https://wordpress.org/showcase/","https://wordpress.org/plugins/"]
s24=["https://www.xing.com/terms","https://www.xing.com/companies","https://advertising.xing.com/","https://tech.xing.com/?gi=7e855a4f8ebb","https://www.xing.com/profile/Sascha_Jonas3","https://tech.xing.com/","https://www.xing.com/profile/Beatrice_Jansen","https://www.xing.com/profile/Iveta_Donaldson","https://www.xing.com/profile/Michael_Bohne3","https://www.xing.com/profile/Tobias_Duchscherer"]
s25=["https://www.yelp.com/","https://www.yelp.com/toronto","https://www.yelp.com/calgary","https://www.yelp.com/user_details?userid=j-aO5H9GePaw3c_saBd-aw","https://www.yelp.com/guidelines","https://www.yelp.com/edmonton","https://www.yelp.com/waterford","https://www.yelp.com/vancouver","https://www.yelp.com/ottawa","https://www.yelp.com/singapore"]
s26=["https://gaming.youtube.com/","https://www.youtube.com/bbcnews","https://tv.youtube.com/welcome/","https://studio.youtube.com/","https://www.youtube.com/html5","https://www.youtube.com/new","https://support.google.com/youtube/answer/2814000?hl=en","https://www.youtube.com/user/pokemon","https://www.youtube.com/channel/UCB0d0JLn1WcGYcwwZ87d2LA","https://support.google.com/youtube/answer/1714323?hl=en"]
yahoo_links = [s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21,s22,s23,s24,s24,s25,s26]
print(yahoo_links[18])
sites=["answers.com","ask.com","blogger.com", "facebook.com", "flickr.com" ,"girlsaskguys.com" ,"imgur.com","instagram.com","last.fm",
		"libre.fm","linkedin.com","match.com","pinterest.com","quora.com","raptr.com","reddit.com","stackoverflow.com" ,"tripadvisor.com","tumblr.com",
		"twitter.com","viadeo.com","wikipedia.org","wordpress.org","xing.com","yelp.com","youtube.com"]

s1=["http://www.answers.com/","https://www.answers.com/Q/FAQ/5091","http://www.answers.com/Q/FAQ/2885","https://www.answers.com/Q/FAQ/7493","https://www.answers.com/Q/FAQ/4148-2","http://wiki.answers.com/help/asking_questions","http://www.answers.com/Q/FAQ/1839","https://www.answers.com/Q/FAQ/7505-2","https://www.answers.com/Q/FAQ/10447-3","http://www.answers.com/Q/FAQ/2148"]
s2=["http://help.ask.com/link/portal/30015/30018/ArticleFolder/11/Ask-com-Browser-Toolbar","http://help.ask.com/ics/support/default.asp?deptID=30018&task=knowledge&questionID=230","https://hp.tb.ask.com/tbask/index.html?p2=^UX^xdm578^S10474^us&n=780c7317&ptb=22D0EFEF-1AF4-4911-BE20-67F032677E7D&qs=fn","http://help.ask.com/link/portal/30015/30018/Article/1/How-do-I-remove-the-Ask-com-Toolbar","http://help.ask.com/ics/support/default.asp?deptID=30018","http://help.ask.com/link/portal/30015/30018/Article/134","https://www.ask.com/","http://apn.ask.com/","http://hp.ask.com/onlinemapfinder/s16311/index.html?p2=%5EBA5%5Exdm133%5ES16351%5Eus&ptb=DD4D7D76-555A-4CB8-A6AA-A6DD9B840CC7&si=245051_Work-ieff&n=782A33E4"]
s3=["https://www.blogger.com/home","https://blogger.com/editor/static_files/blank_quirks.html","https://www.blogger.com/login.g","https://www.blogger.com/profile/12522565235980454675","https://www.blogger.com/?rinli=1","https://www.blogger.com/profile/04486298891295312827","https://www.blogger.com/profile/10316114807344544892","https://www.blogger.com/profile/16820399856274245684","https://www.blogger.com/profile/14340145740286368529","https://www.blogger.com/content.g?hl=en&authuser=0&bpli=1"]
s4=["http://www.facebook.com/r.php","http://www.facebook.com/Bing","https://apps.facebook.com/criminalcase/","https://mbasic.facebook.com/","http://www.facebook.com/find-friends/","https://apps.facebook.com/wordswithfriends/","https://www.facebook.com/recover/initiate","http://www.facebook.com/people-search.php","http://www.facebook.com/youtube","http://www.facebook.com/help/"]
s5=["https://www.flickr.com/photos/tags/stormydaniels/","https://www.flickr.com/","https://www.flickr.com/photos/tags/ladyboy/","https://www.flickr.com/photos/tags/sexyfeet/","https://www.flickr.com/photos/tags/cunts/","https://www.flickr.com/photos/12958857@N05/","https://www.flickr.com/photos/blue-diesels/","https://www.flickr.com/photos/","https://www.flickr.com/tools/","https://www.flickr.com/photos/76237188@N03/favorites/"]
s6=["https://www.girlsaskguys.com/","https://www.girlsaskguys.com/ask-question","https://www.girlsaskguys.com/social-relationships/q57326-truth-questions","https://www.girlsaskguys.com/guys-behavior","https://www.girlsaskguys.com/sexual-health/q112174-is-6-5-inches-small","https://www.girlsaskguys.com/girls-behavior","https://www.girlsaskguys.com/sexual-behavior","https://www.girlsaskguys.com/flirting","https://www.girlsaskguys.com/dating/q2604614-match-com-question-what-does-the-open-green-circle-mean-how-long","https://www.girlsaskguys.com/guys-behavior/q784410-why-against-law-for-person-living-in"]
s7=["https://i.imgur.com/wrDS2xn.gifv","https://i.imgur.com/Ar4Y2m8.gifv","https://i.imgur.com/Ar91xOK.gifv","https://i.imgur.com/K1uwXen.gifv","https://i.imgur.com/SbPCocn.gifv","https://i.imgur.com/fkhklEX.gifv","https://i.imgur.com/FWSntf7.gifv","https://i.imgur.com/CUrslNO.gifv","https://i.imgur.com/zzKK9Hl.gifv","https://i.imgur.com/ZPFcffq.gifv"]
s8=["https://www.instagram.com/explore/tags/kathniel/","https://www.instagram.com/explore/tags/fiftyshadesfreed/","https://www.instagram.com/explore/tags/helenefischer/","https://www.instagram.com/explore/tags/tïts/","https://www.instagram.com/explore/tags/justinbieber/","https://www.instagram.com/explore/tags/nadechyaya/","https://www.instagram.com/explore/tags/brumar/","https://www.instagram.com/explore/tags/fitness/","https://www.instagram.com/explore/tags/jelena/","https://www.instagram.com/1789_toho/"]
s9=["https://www.last.fm/","https://www.last.fm/music/Atif+Aslam","https://www.last.fm/music","https://www.last.fm/music/Kishore+Kumar","https://www.last.fm/music/Westlife","https://www.last.fm/music/jj","https://www.last.fm/music/+free-music-downloads","https://www.last.fm/join","https://www.last.fm/music/Maher+Zain","https://secure.last.fm/login"]
s10=["https://libre.fm/login.php","https://libre.fm/listen.php?tag=classical","https://libre.fm/register.php","https://libre.fm/reset.php","https://libre.fm/user/RJules3/stats","https://libre.fm/user/jonwarren/stats","https://libre.fm/","https://libre.fm/artist/Alexander+Blu/","http://turtle.libre.fm/","https://libre.fm/listen.php"]
s11=["https://in.linkedin.com/","https://www.linkedin.com/uas/login","https://www.linkedin.com/company/login","https://developer.linkedin.com/","https://business.linkedin.com/sales-solutions/sales-navigator","https://www.linkedin.com/company/l&t-infotech","https://business.linkedin.com/marketing-solutions/company-pages","https://business.linkedin.com/marketing-solutions/ads","https://www.linkedin.com/post/new","https://business.linkedin.com/"]
s12=["https://www4.match.com/login","https://in.match.com/login/forgotemail/","https://www4.match.com/logout/?lid=3","https://www.match.com/cpx/en-us/landing/display/84123/","https://www.match.com/","https://datingtips.match.com/flirt-girl-chatting-13197209.html","https://ie.match.com/","https://www.match.com/cpx/en-us/partner/yahoo/channel/","http://careers.match.com/","https://ie.match.com/m/"]
s13=["https://www.pinterest.com/","https://www.pinterest.com/explore/junk-art/","https://www.pinterest.com/pin/573223858791988548/","https://www.pinterest.com/explore/seasons-kindergarten/","https://www.pinterest.com/pin/567172146804044781/","https://www.pinterest.com/explore/cute-dog-quotes/","https://www.pinterest.com/pin/507006870530099894/","https://www.pinterest.com/pin/283726845253029618/","https://www.pinterest.com/pin/84583299225144026/","https://www.pinterest.com/pin/146226319124661185/"]
s14=["https://www.quora.com/What-is-the-password-to-open-an-e-Aadhaar-card","https://www.quora.com/","https://www.quora.com/topic/China","https://www.quora.com/How-many-watts-are-equal-to-1-unit-in-an-electricity-bill","https://www.quora.com/How-do-you-track-a-Western-Union-money-order-online","https://www.quora.com/How-much-is-one-million-and-one-billion-in-lakhs-and-crores","https://www.quora.com/How-do-I-disable-Windows-10-update-assistant","https://supermonk.quora.com/","https://www.quora.com/How-much-money-in-US-dollars-is-1-crore-rupees","https://www.quora.com/What-can-cause-foam-to-come-out-from-the-mouth-and-nose-of-a-dead-body"]
s15=["http://raptr.com/amd","http://raptr.com/","http://raptr.com/bestiality/games","http://raptr.com/community/highlights/discussions","http://raptr.com/download","http://about.raptr.com/goodbye-raptr/","http://raptr.com/amd/games","http://about.raptr.com/","http://raptr.com/login/reset","http://raptr.com/free-games"]
s16=["https://www.reddit.com/","https://www.reddit.com/r/soccer/","https://www.reddit.com/r/aww/comments/83psdv/neighboring_husky_boi_returns_an_awoo/","https://www.reddit.com/r/movies/comments/828cyn/john_boyega_here_ask_me_anything/","https://reddit.com/r/ChoosingBeggars/comments/83ftyj/this_other_person_i_hired_sucks_so_i_want_to_hire/","https://www.reddit.com/r/xboxone/","https://reddit.com/r/mildlyinfuriating/comments/8166ul/these_pencils_suck/","https://www.reddit.com/r/wholesomebpt/comments/82fqzs/good_deeds_and_blooming_seeds/","https://www.reddit.com/r/SheBelievesCup2018/","https://reddit.com/r/news/comments/825i4n/north_korea_made_as_much_as_200_million_from/"]
s17=["https://stackoverflow.com/","https://stackoverflow.com/questions/6288122/checking-oracle-sid-and-database-name","https://stackoverflow.com/questions/10195451/sql-inner-join-with-3-tables","https://stackoverflow.com/questions/11824501/inner-joining-three-tables","https://stackoverflow.com/questions/19641597/what-is-segmentation-fault-core-dumped","https://stackoverflow.com/questions/5774970/run-jar-file-in-command-prompt","https://stackoverflow.com/questions/29432629/correlation-matrix-using-pandas","https://stackoverflow.com/jobs","https://stackoverflow.com/questions/19721416/formula-to-convert-date-to-number","https://stackoverflow.com/questions/15675414/add-attachement-to-outlook-with-varying-file-names"]
s18=["https://www.tripadvisor.com/","https://www.tripadvisor.com/Attractions-g188590-Activities-Amsterdam_North_Holland_Province.html","https://www.tripadvisor.com/Attractions-g35805-Activities-Chicago_Illinois.html","https://www.tripadvisor.com/Attractions-g187147-Activities-Paris_Ile_de_France.html","https://www.tripadvisor.com/Attractions-g45963-Activities-Las_Vegas_Nevada.html","https://www.tripadvisor.com/Attractions-g60878-Activities-Seattle_Washington.html","https://www.tripadvisor.com/Attractions-g293974-Activities-Istanbul.html","https://www.tripadvisor.com/Attractions-g60713-Activities-San_Francisco_California.html","https://www.tripadvisor.com/Hotels-g294217-Hong_Kong-Hotels.html","https://www.tripadvisor.com/Hotels"]
s19=["https://www.tumblr.com/","http://srbachchan.tumblr.com/","http://wikihow.tumblr.com/","https://obscurus-sims.tumblr.com/","https://pasldan.tumblr.com/dasibogitv","http://guncontrolmarch.tumblr.com/","http://reallyfunnyjokes.tumblr.com/","http://russia-instagram.tumblr.com/","http://jessiichavez.tumblr.com/","http://badkidsjokes.tumblr.com/"]
s20=["https://mobile.twitter.com/account","https://tweetdeck.twitter.com/","https://twitter.com/login/","https://ads.twitter.com/","https://twitter.com/asadowaisi","https://twitter.com/ideacellular","https://twitter.com/sciencedaily","https://business.twitter.com/","https://analytics.twitter.com/","https://about.twitter.com/"]
s21=["http://in.viadeo.com/en/","http://in.viadeo.com/en/profile/capitalstars.financial.research","http://in.viadeo.com/en/profile/boris.denoual","http://in.viadeo.com/en/profile/pooja-singh.bhandari1","http://in.viadeo.com/en/profile/somnath.chatterjee12","http://in.viadeo.com/en/profile/vijendra.poonia","http://in.viadeo.com/en/groups/?containerId=002rhucs3dgvqqu","http://in.viadeo.com/en/profile/sridevi.rao","http://in.viadeo.com/en/questions/repondre/?questionId=0021y0smng6owspm","http://www.viadeo.com/en/mentions-legales"]
s22=["https://en.wikipedia.org/wiki/CAPTCHA","https://simple.wikipedia.org/wiki/Rain","https://en.wikipedia.org/wiki/Sachin_(actor)","https://simple.wikipedia.org/wiki/Hindi","https://simple.wikipedia.org/wiki/Wikipedia:Basic_English_picture_wordlist","https://en.wikipedia.org/wiki/Amroha","https://en.wikipedia.org/wiki/Confusion","https://en.wikipedia.org/wiki/Extranet","https://en.wikipedia.org/wiki/Organza","https://en.wikipedia.org/wiki/HSE"]
s23=["https://wordpress.org/","https://codex.wordpress.org/Child_Themes","https://codex.wordpress.org/Twenty_Seventeen","https://codex.wordpress.org/WordPress_Widgets","https://codex.wordpress.org/","https://codex.wordpress.org/New_To_WordPress_-_Where_to_Start","https://wordpress.org/download/","https://codex.wordpress.org/Updating_WordPress","https://codex.wordpress.org/CSS","https://wordpress.org/showcase/"]
s24=["https://www.xing.com/en","https://dev.xing.com/developers","https://www.xing.com/xtm","https://recruiting.xing.com/en/contact/","https://www.xing.com/jobmanager/products","https://recruiting.xing.com/en/","https://tech.xing.com/","https://dev.xing.com/plugins/login_with","https://dev.xing.com/logo_rules","https://corporate.xing.com/fileadmin/department/investorrelations/Publikationen/XING_AG_results_FY_2012.pdf"]
s25=["https://yelp.com/biz/eastern-bloc-new-york","https://yelp.com/biz/mokai-lounge-miami-beach","https://www.yelp.com/biz/access-insurance-company-atlanta-2","https://yelp.com/biz/torchys-tacos-austin","https://yelp.com/biz/oriental-buffet-sarasota","https://yelp.com/biz/tasty-made-lancaster","https://yelp.com/biz/carvalhos-brazilian-kitchen-scottsdale","https://yelp.com/biz/deluxe-station-diner-newton","https://www.yelp.com/biz/luscious-dumplings-san-gabriel-3","https://yelp.com/biz/now-and-then-second-hand-store-orange"]
s26=["https://gaming.youtube.com/","https://www.youtube.com/advanced_settings","https://www.youtube.com/watch?v=9Bxik6kLEbM","https://gaming.youtube.com/ice_poseidon/live","https://www.youtube.com/watch?v=38aIMNJKS-g","https://gaming.youtube.com/Swaggxbl","https://youtube.com/watch?v=qt4v-kXP8F4","https://youtube.com/watch?v=_I_D_8Z4sJE","https://www.youtube.com/watch?v=Ya_4C3jSsn0","https://youtube.com/watch?v=P6CwU6i6ick"]

bing_links = [s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21,s22,s23,s24,s24,s25,s26]