# -*- coding: utf-8 -*-
# @Author: rajeshneti
# @Date:   2018-04-16 12:10:33
# @Last Modified by:   rajeshneti
# @Last Modified time: 2018-04-16 13:24:32
sites=["answers.com","ask.com","blogger.com", "facebook.com", "flickr.com" ,"girlsaskguys.com" ,"imgur.com","instagram.com","last.fm",
		"libre.fm","linkedin.com","match.com","pinterest.com","quora.com","raptr.com","reddit.com","stackoverflow.com" ,"tripadvisor.com","tumblr.com",
		"twitter.com","viadeo.com","wikipedia.org","wordpress.org","xing.com","yelp.com","youtube.com"]
s1=["http://www.answers.com/","http://www.answers.com/Q/","http://www.answers.com/Q/What_is_the_value_of_a_1915_Susan_B_Anthony_half_Dollar","http://www.answers.com/Q/What_did_Grandma_Moses_children_call_her","http://www.answers.com/Q/What_is_the_phone_number_of_the_Mount_Carmel_Library_in_Mount_Carmel","http://www.answers.com/Q/Did_Moses_really_cross_the_red_sea","http://www.answers.com/Q/Can_you_travel_with_a_gas_stove_lighter_on_an_airplane","http://qa.answers.com/Q/What_river_flowing_to_the_Mediterranean_starts_with_the_letter_E","http://qa.answers.com/Q/Is_Africa_in_the_Middle_East_or_southeast","http://www.answers.com/Q/Did_hitler_invading_sweeden_start_World_War_2"]
s2=["https://www.reference.com/science","https://www.reference.com/education","https://www.reference.com/technology","https://www.reference.com/geography","https://www.reference.com/food","https://www.reference.com/history","https://www.reference.com/history","https://www.reference.com/history","https://www.reference.com/history","https://www.reference.com/history"]
s3=["https://www.blogger.com/about/?r=2","https://plus.google.com/118027515659458990484","https://plus.google.com/113348569517506764394","https://plus.google.com/110628371959257478941","https://plus.google.com/+fuxoft","https://www.blogger.com/profile/1","https://productforums.google.com/forum/?authuser=0#!forum/blogger","https://productforums.google.com/forum/#!forum/blogger","https://plus.google.com/+GuilleSGOTTLOSEN","https://plus.google.com/111188340418150286510"]
s4=["https://www.facebook.com/pasargadtabac/","https://www.facebook.com/BritesideDelivery/","https://www.facebook.com/JesusCalling/","https://www.facebook.com/newyou6weekchallenge/","https://www.facebook.com/feminamissindia/","https://www.facebook.com/marathigirls11/","https://www.facebook.com/ktla5/","https://www.facebook.com/psbacademy/","https://www.facebook.com/soundheartsfestival/","https://www.facebook.com/Ddfreekibaat/"]
s5=["https://www.flickr.com/creativecommons/?ytcheck=1&new_session=1","https://www.flickr.com/cameras?ytcheck=1&new_session=1","https://www.flickr.com/?ytcheck=1&new_session=1","https://flickr.com/","https://www.flickr.com/create","https://www.flickr.com/explore/","https://www.flickr.com/photos/flickr/galleries?rb=1","https://www.flickr.com/map","https://www.flickr.com/photos/crehealth","https://www.flickr.com/photos/laurattphoto"]
s6=["https://www.girlsaskguys.com/topics","https://www.girlsaskguys.com/popular","https://www.girlsaskguys.com/dating","https://www.girlsaskguys.com/poll","https://www.girlsaskguys.com/relationships","https://www.girlsaskguys.com/no-opinions","https://www.girlsaskguys.com/live-feed","https://www.girlsaskguys.com/guys-behavior","https://www.girlsaskguys.com/technology-internet","https://www.girlsaskguys.com/dating/q3069693-stranger-dating"]
s7=["https://imgur.com/","https://imgur.com/memegen","https://smarteck.imgur.com/","https://imgurinc.com/press/","https://imgur.com/gallery","https://underworldlarp.imgur.com/","https://imgur.com/dooS7Dk","https://cavinanderson.imgur.com/","https://imgur.com/PWgkluX","https://imgur.com/AHYwI9m"]
s8=["https://www.instagram.com/juandediospantoja/","https://www.instagram.com/mangekimambi_/","https://www.instagram.com/um_naif_5/","https://www.instagram.com/carolinacruzosorio/","https://www.instagram.com/sophiefontanel/","https://www.instagram.com/baileysok1/","https://www.instagram.com/sebastianyatra/","https://www.instagram.com/gracielelacerdaoficial/","https://www.instagram.com/lokhandeankita/","https://www.instagram.com/757cece/"]
s9=["https://www.last.fm/","https://www.last.fm/events","https://www.last.fm/api","https://build.last.fm/","https://www.last.fm/about","https://www.last.fm/features","https://www.last.fm/passwordsecurity","https://www.last.fm/musicmanager","http://status.last.fm/","https://www.last.fm/subscribe"]
s10=["https://libre.fm/podcast","https://libre.fm/","https://libre.fm/api/","https://turtle.libre.fm/","https://libre.fm/user/balleyne","https://libre.fm/user/tobyink","https://libre.fm/listen.php","https://libre.fm/donate.php","https://libre.fm/register.php","https://libre.fm/login.php"]
s11=["https://www.microsoft.com/en-us/investor/","https://www.linkedin.com/in/sladner","https://www.linkedin.com/school/ist/","https://in.linkedin.com/jobs/","https://www.linkedin.com/school/fiap/","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQE9CH6GP5VSUAAAAWLNUmWAgUjHbeUj-mceW4XHLzvxopxMgzfcoUP7421gd5qc-HaC9U-KjXSQX-De6gwz-OY0bEoHmRkXva91V3nsJQ2arElHsTYZcbtht4PRHiIsmoWrJ7o=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAwwa7HAx.;_ylu=X3oDMTEyMWU3cWt0BGNvbG8Dc2czBHBvcwM2BHZ0aWQDQjEzOThfMQRzZWMDc3I-/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fin%2fblouvet&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fblouvet%2F","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQHJSs3XiwVj1gAAAWLNUm1QnHOVebnyPYzIj-ElL_RxMR8rAKkRAcQG9h5xSKSip7WEE81c6I6jPE-EoawJY9NVRE8j3kiynrIiK4vHJDHt8g_dgCoe4lmpwlbgYBC3Gwtiqmc=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAxAa7HAx.;_ylu=X3oDMTEyaG84OWRlBGNvbG8Dc2czBHBvcwM3BHZ0aWQDQjEzOThfMQRzZWMDc3I-/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fin%2fbrockfe&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fbrockferguson","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQGXa4vX5oV9_gAAAWLNUoiogXdM8LCP7ffuVwzavdK74rwUxJwSacVlBRXIk9ESoG3J43plIzLiepYwvQuYXZosMQDEpInHl-WOL0guwqNZkifrmJ2UCW3AHYsBd_UKRwTCaKs=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAxga7HAx.;_ylu=X3oDMTEyMWU5dm1tBGNvbG8Dc2czBHBvcwM5BHZ0aWQDQjEzOThfMQRzZWMDc3I-/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fcompany%2fpe&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fpearson","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQHtoL-J_ZLIqAAAAWLNUoyQTsxNJKEbCszCJ4tdxkRbPKCBYhzb9VoKT_D3ySAUAzRr_0A5Yi4SqGW0PQF9xcmrbxDvV3ZKy-i3UJyGanxOvFJYGlzdcpPM2Iiiz7ePxAATQrQ=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAxwa7HAx.;_ylu=X3oDMTEzZGNuYzczBGNvbG8Dc2czBHBvcwMxMAR2dGlkA0IxMzk4XzEEc2VjA3Ny/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fcompany%2fxi&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fxilinx","https://www.linkedin.com/authwall?trk=gf&trkInfo=AQGCsfVOIsbvcgAAAWLNUoyQkbunGO64C3oEb3kaQzi_OBqLNIiA0W-PrJEQKhNqCu1ksQR9nIO9BzrDIQdk_7ystb5sgaHh8tUXmwhZ6DvRkVCWkc6rZcLkZERKMHkoQ1Zp9W8=&originalReferer=https://r.search.yahoo.com/_ylt=A2oKmJRZTtRax1AAxQa7HAx.;_ylu=X3oDMTEyYmg5dHNsBGNvbG8Dc2czBHBvcwM4BHZ0aWQDQjEzOThfMQRzZWMDc3I-/RV=2/RE=1523891929/RO=10/RU=https%3a%2f%2fwww.linkedin.com%2fin%2fvincent&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fvincentgrady"]
s12=["https://ie.match.com/","https://in.match.com/dnws/cpx/intl/match/IndexPage/","http://www.match.com.ve/","https://in.match.com/dnws/magazine/","https://th.match.com/dnws/cpx/intl/match/IndexPage/","http://latino.match.com/","https://datingtips.match.com/","https://sg.match.com/dnws/cpx/intl/match/IndexPage/","https://in.match.com/dnws/help/help.aspx","https://in.match.com/dnws/hostevent/"]
s13=["https://in.pinterest.com/crpolo1/?autologin=true","https://in.pinterest.com/lea7505/","https://in.pinterest.com/jennydasilvamar/","https://in.pinterest.com/msladyleo04/?autologin=true","https://in.pinterest.com/aranthechef/","https://in.pinterest.com/yuwdhie7/","https://in.pinterest.com/bethanyellen7/?autologin=true","https://in.pinterest.com/kdbug2999/?autologin=true","https://in.pinterest.com/abbysalright/?autologin=true","https://in.pinterest.com/someblackguy087/"]
s14=["https://blog.quora.com/","https://thatsiitk.quora.com/","https://business.quora.com/","https://kavitaa.quora.com/","https://debunkingdoomsday.quora.com/","https://supermonk.quora.com/","https://de.quora.com/join?code=0&join_source=1&ref","https://megaflix69.quora.com/","https://alison60.quora.com/","https://it.quora.com/join?code=0&join_source=1&ref"]
s15=["http://raptr.com/","http://raptr.com/eisserjuriya/wall","http://raptr.com/thegeneralnws/wall","http://raptr.com/haley/wall","http://raptr.com/download","http://raptr.com/amd","http://raptr.com/intel","http://raptr.com/raptr_master","http://raptr.com/lgc41986/wall","http://raptr.com/borrylord/about"]
s16=["https://www.reddit.com/r/NBAPlayoffs_2018/comments/8chp81/freereddit_stream_pacers_vs_cavaliers_2018/","https://www.reddit.com/r/WorldSportslivefree/comments/8c7w6t/watchswansea_city_vs_everton_live_stream_2018/","https://www.reddit.com/r/WarriorsvsSpursLive/comments/8chcb6/livefreebasketball_indiana_pacers_vs_cleveland/","https://www.reddit.com/r/WarriorsvsSpursLive/comments/8cfmvv/watchhdmanchester_united_vs_west_brom_live_stream/","https://www.reddit.com/r/ChiefsvsHurricanesliv/comments/8c8d2e/livefreefight_ksw_43_soldic_vs_du_plessis_live/","https://www.reddit.com/r/nascarliveupdate/comments/8ch916/watchfreenascar_cup_series_food_city_500_live/","https://www.reddit.com/r/AmstelGoldRace2018/comments/8cfrrq/tro_bro_leon_2018_live_stream_reddit_free/","https://www.reddit.com/r/WarriorsvsSpursLive/comments/8cgpnc/angels_vs_royals_live_stream_reddit_free/","https://www.reddit.com/r/WorldSportslivefree/comments/8c7uhi/epl_streams_crystal_palace_vs_brighton_and_ha/","https://www.reddit.com/r/nba/comments/8ch3y4/game_thread_indiana_pacers_4834_cleveland/"]
s17=["https://stackoverflow.com/","https://es.stackoverflow.com/","https://stackoverflow.blog/","https://stackoverflow.com/jobs","https://www.youtube.com/watch?v=9UZbGgXvCCA","https://insights.stackoverflow.com/trends","https://stackoverflow.com/questions","https://insights.stackoverflow.com/survey/2016","https://insights.stackoverflow.com/trends?tags=r%2Cstatistics","https://insights.stackoverflow.com/survey/2018/"]
s18=["https://www.tripadvisor.in/","https://careers.tripadvisor.com/","https://itunes.apple.com/app/tripadvisor-hotels-flights-restaurants/id284876795?mt=8","https://www.tripadvisor.com/TravelersChoice","https://www.tripadvisor.com/VacationRentalsBlog/","https://www.tripadvisor.com/members/474andyt","https://www.tripadvisor.com/members/JoeyIamarino","https://www.tripadvisor.com/members/wendylB3942PW","https://www.tripadvisorsupport.com/hc/en-us/articles/200614797","https://www.tripadvisorsupport.com/hc/en-us/articles/200615037"]
s19=["","","","","","","","","",""]
s20=["https://twitter.com/instagram","https://twitter.com/ea","https://twitter.com/russianembassy","https://twitter.com/eminem","https://twitter.com/barackobama","https://twitter.com/bet49s","https://twitter.com/prefpolice","https://twitter.com/realdonaldtrump","https://twitter.com/poetastrologers","https://twitter.com/marvel"]
s21=["https://dz.viadeo.com/en/","http://www.figaroclassifieds.fr/pages/7018-emploi","https://sn.viadeo.com/en/","https://lu.viadeo.com/en/","https://ci.viadeo.com/en/","https://mg.viadeo.com/en/","https://bf.viadeo.com/en/","https://cd.viadeo.com/en/","https://ca.viadeo.com/en/","https://ch.viadeo.com/en/"]
s22=["https://www.wikipedia.org/","https://en.wikipedia.org/wiki/Ben_Baldanza","https://pl.wikipedia.org/wiki/Kieran_Trippier","https://en.wikipedia.org/wiki/Braille","https://pl.wikipedia.org/wiki/Codogno","https://en.wikipedia.org/wiki/Bebop_scale","https://en.wikipedia.org/wiki/Patrick_Cramer","https://en.wikipedia.org/wiki/Varun_Sharma","https://en.wikipedia.org/wiki/Anna_Castillo","https://en.wikipedia.org/wiki/Access_Point_Name"]
s23=["https://apps.wordpress.com/support/","https://make.wordpress.org/cli/","https://apps.wordpress.com/contribute/","https://apps.wordpress.com/","https://wordpress.org/about/","https://wordpress.org/themes/","https://wordpress.org/gutenberg/","https://planet.wordpress.org/","https://wordpress.org/showcase/","https://wordpress.org/plugins/"]
s24=["https://www.xing.com/terms","https://www.xing.com/companies","https://advertising.xing.com/","https://tech.xing.com/?gi=7e855a4f8ebb","https://www.xing.com/profile/Sascha_Jonas3","https://tech.xing.com/","https://www.xing.com/profile/Beatrice_Jansen","https://www.xing.com/profile/Iveta_Donaldson","https://www.xing.com/profile/Michael_Bohne3","https://www.xing.com/profile/Tobias_Duchscherer"]
s25=["https://www.yelp.com/","https://www.yelp.com/toronto","https://www.yelp.com/calgary","https://www.yelp.com/user_details?userid=j-aO5H9GePaw3c_saBd-aw","https://www.yelp.com/guidelines","https://www.yelp.com/edmonton","https://www.yelp.com/waterford","https://www.yelp.com/vancouver","https://www.yelp.com/ottawa","https://www.yelp.com/singapore"]
s26=["https://gaming.youtube.com/","https://www.youtube.com/bbcnews","https://tv.youtube.com/welcome/","https://studio.youtube.com/","https://www.youtube.com/html5","https://www.youtube.com/new","https://support.google.com/youtube/answer/2814000?hl=en","https://www.youtube.com/user/pokemon","https://www.youtube.com/channel/UCB0d0JLn1WcGYcwwZ87d2LA","https://support.google.com/youtube/answer/1714323?hl=en"]
yahoo_links = [s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21,s22,s23,s24,s24,s25,s26]